# Generated by Django 2.1.5 on 2020-04-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cate',
            options={'verbose_name_plural': 'Cate'},
        ),
    ]
